import { IProduct } from './iproduct';

export let ProductList: IProduct[] = [
  {
    id: 1,
    img: 'https://images.pexels.com/photos/248526/pexels-photo-248526.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    name: 'Mobile',
    description: 'Iphone',
    price: 25000,
    onSale: true,
    discount: 0.02,
    quantity: 5,
  },
  {
    id: 2,
    img: 'https://images.pexels.com/photos/7974/pexels-photo.jpg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    name: 'Laptob',
    description: 'MacBook Pro',
    price: 7000,
    onSale: false,
    discount: 0.1,
    quantity: 10,
  },
  // {
  //   id: 3,
  //   img: 'https://images.pexels.com/photos/601316/pexels-photo-601316.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
  //   name: 'skirt',
  //   description: 'my skirt ',
  //   price: 500,
  //   onSale: true,
  //   discount: 0.25,
  //   quantity: 5,
  // },
  // {
  //   id: 4,
  //   img: 'https://images.pexels.com/photos/996329/pexels-photo-996329.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
  //   name: 't-shirt',
  //   description: 'my t-shirt ',
  //   price: 300,
  //   onSale: false,
  //   discount: 0.1,
  //   quantity: 0,
  // },
  // {
  //   id: 5,
  //   img: 'https://images.pexels.com/photos/18105/pexels-photo.jpg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
  //   name: 'laptop',
  //   description: 'my laptop ',
  //   price: 15000,
  //   onSale: true,
  //   discount: 0.15,
  //   quantity: 20,
  // },
];
